CREATE DATABASE BuildQueryTest2
USE BuildQueryTest2
--Dion Finnerty
--103545669


/*
--TASK1--
RELATIONAL SCHEMA


ORGANISATION(OrgID, OrganisationName)
PRIMARY KEY(OrgID)

CLIENT(ClientID, OrgID, Name, Phone)
PRIMARY KEY(ClientID)
FOREIGN KEY(OrgID)  REFERENCES ORGANISATION

ORDER(DateTimePlaced, ClientID, DeliveryAddress)
PRIMARY KEY(DateTimePlaced, ClientID)
FOREIGN KEY(ClientID) REFERENCES CLIENT

MENUITEM(ItemID, Description, ServesPerUnit, UnitPrice)
PRIMARY KEY(ItemID)

ORDERLINE(ClientID, DateTimePlaced, ItemID, Qty)
PRIMARY KEY(ClientID, DateTimePlaced, ItemID)
FOREIGN KEY(ClientID, DateTimePlaced) REFERENCES ORDER
FOREIGN KEY(ItemID) REFERENCES MENUITEM

DROP TABLE ORGANISATION5669
DROP TABLE CLIENT5669
DROP TABLE ORDER5559
DROP TABLE MENUITEM5669
DROP TABLE ORDERLINE5669
DROP TABLE ORGANISATION
DROP TABLE CLIENT
DROP TABLE ORDER
DROP TABLE MENUITEM
DROP TABLE ORDERLINE
*/


--TASK2 
CREATE TABLE ORGANISATION5669(
    OrgID NVARCHAR(4), 
    OrganisationName NVARCHAR(200) UNIQUE NOT NULL,
    PRIMARY KEY(OrgID)
)

CREATE TABLE CLIENT5669(
    ClientID INT,  
    [Name] NVARCHAR(100) NOT NULL, 
    Phone NVARCHAR(15) UNIQUE NOT NULL,
    OrgID NVARCHAR(4),
    PRIMARY KEY(ClientID),
    FOREIGN KEY(OrgID) REFERENCES ORGANISATION5669
)

CREATE TABLE ORDER5669(
    ClientID INT, 
    DateTimePlaced DATE, 
    DeliveryAddress NVARCHAR(MAX) NOT NULL,
    PRIMARY KEY(ClientID, DateTimePlaced),
    FOREIGN KEY(ClientID) REFERENCES CLIENT5669
)

CREATE TABLE MENUITEM5669(
    ItemID INT, 
    [Description] NVARCHAR(100) UNIQUE NOT NULL, 
    ServesPerUnit INT, 
    UnitPrice MONEY NOT NULL,
    PRIMARY KEY(ItemID),
    CONSTRAINT CHK_ServePerUnit CHECK (ServesPerUnit > 0)
)

CREATE TABLE ORDERLINE5669(
    ItemID INT, 
    ClientID INT, 
    DateTimePlaced DATE, 
    Qty INT NOT NULL,
    PRIMARY KEY(ClientID, DateTimePlaced, ItemID),
    FOREIGN KEY (ClientID, DateTimePlaced) REFERENCES ORDER5669,
    FOREIGN KEY(ItemID) REFERENCES MENUITEM5669,
    CONSTRAINT CHK_Qty CHECK (Qty > 0)
)

SELECT * FROM  ORGANISATION5669
SELECT * FROM  CLIENT5669
SELECT * FROM  ORDER5559
SELECT * FROM MENUITEM5669
SELECT * FROM  ORDERLINE5669

